# See GitHub's docs for more information on this file:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to Go modules every week
      interval: "weekly"
    groups:
      # Group terraform-plugin-framework dependencies together
      terraform:
        applies-to: version-updates
        patterns:
          - "*terraform-plugin-*"
        update-types:
          - "patch"
          - "minor"

  # Maintain dependencies for Go modules for tools
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      # Check for updates to Go modules every week
      interval: "weekly"
    groups:
      # Group all linting tools together
      linters:
        applies-to: version-updates
        patterns:
          - "*tfproviderlint*"
          - "*golangci-lint*"
          - "*terrafmt*"
          - "*tflint*"
          - "*impi*"
        update-types:
          - "minor"
    # Ignore patches for linters, only update for minor versions
    ignore:
      - dependency-name: "*tfproviderlint*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "*golangci-lint*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "*terrafmt*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "*tflint*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "*impi*"
        update-types: ["version-update:semver-patch"]
