issues:
  exclude-rules:
    # Exclude issues bypassing staticcheck.conf
    - linters:
        - staticcheck
      text: "SA1019:"

    - linters:
        - unparam
      text: "always receives"

  max-same-issues: 0

linters:
  disable-all: true
  enable:
    # - deadcode
    - errcheck
    - copyloopvar
    - gofmt
    - mnd
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck
    # - structcheck
    - unconvert
    - unparam
    # - varcheck
    - govet

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).SetNewComputed
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).ForceNew
      - io:Close
  
  mnd:
    checks:
      - argument
    ignored-functions:
      - request.ConstantWaiterDelay
      - request.WithWaiterMaxAttempts
      # Terraform Plugin SDK
      - resource.Retry
      - schema.DefaultTimeout
      - validation.*
      # Go
      - make
      - strconv.FormatFloat
      - strconv.FormatInt
      - strconv.ParseFloat
      - strconv.ParseInt
      - strings.SplitN
  nolintlint:
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - unparam
      - gomnd

run:
  timeout: 35m