// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package sso

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/patrickcping/pingone-go-sdk-v2/management"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework/customtypes/pingonetypes"
	"github.com/pingidentity/terraform-provider-pingone/internal/sdk"
)

var (
	_ datasource.DataSource              = &resourceScopesDataSource{}
	_ datasource.DataSourceWithConfigure = &resourceScopesDataSource{}
)

func NewResourceScopesDataSource() datasource.DataSource {
	return &resourceScopesDataSource{}
}

type resourceScopesDataSource serviceClientType

func (r *resourceScopesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_resource_scopes"
}

func (r *resourceScopesDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	resourceConfig, ok := req.ProviderData.(framework.ResourceType)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected the provider client, got: %T. Please report this issue to the provider maintainers.", req.ProviderData),
		)

		return
	}

	r.Client = resourceConfig.LegacyClient.API
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Client not initialised",
			"Expected the PingOne client, got nil.  Please report this issue to the provider maintainers.",
		)
		return
	}
}

type resourceScopesDataSourceModel struct {
	EnvironmentId pingonetypes.ResourceIDValue `tfsdk:"environment_id"`
	Id            pingonetypes.ResourceIDValue `tfsdk:"id"`
	Ids           types.Set                    `tfsdk:"ids"`
	ResourceId    types.String                 `tfsdk:"resource_id"`
}

func (r *resourceScopesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Data source to retrieve all resource_scopes.",
		Attributes: map[string]schema.Attribute{
			"environment_id": framework.Attr_LinkID(
				framework.SchemaAttributeDescriptionFromMarkdown("The ID of the environment to read scopes from. Must be a valid PingOne resource ID."),
			),
			"id": framework.Attr_ID(),
			"ids": schema.SetAttribute{
				ElementType: pingonetypes.ResourceIDType{},
				Computed:    true,
				Description: "The list of resulting IDs of resource_scopes objects that have been successfully retrieved.",
			},
			"resource_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (state *resourceScopesDataSourceModel) readClientResponse(response *management.ResourceScope) diag.Diagnostics {
	var respDiags, diags diag.Diagnostics
	// id
	idValue := framework.PingOneResourceIDToTF(response.GetId())
	state.Id = idValue
	// ids
	state.Ids, diags = types.SetValueFrom(context.Background(), pingonetypes.ResourceIDType{}, response.Ids)
	respDiags.Append(diags...)
	return respDiags
}

func (r *resourceScopesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data resourceScopesDataSourceModel

	if r.Client == nil || r.Client.ManagementAPIClient == nil {
		resp.Diagnostics.AddError(
			"Client not initialized",
			"Expected the PingOne client, got nil.  Please report this issue to the provider maintainers.")
		return
	}

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Read API call logic
	var responseData *management.ResourceScope
	// If an id is provided, read the data source by id
	if !data.ResourceId.IsNull() {
		resp.Diagnostics.Append(framework.ParseResponse(
			ctx,

			func() (any, *http.Response, error) {
				fO, fR, fErr := r.Client.ManagementAPIClient.ResourceScopesApi.ReadOneResourceScope(ctx, data.EnvironmentId.ValueString(), data.ResourceId.ValueString()).Execute()
				return framework.CheckEnvironmentExistsOnPermissionsErrorLegacySdk(ctx, r.Client.ManagementAPIClient, data.EnvironmentId.ValueString(), fO, fR, fErr)
			},
			"ReadOneResourceScope",
			framework.DefaultCustomError,
			sdk.DefaultCreateReadRetryable,
			&responseData,
		)...)
		if resp.Diagnostics.HasError() {
			return
		}
	} else if !data.Name.IsNull() {
		// Get all objects and find the one with the expected name
		resp.Diagnostics.Append(framework.ParseResponse(
			ctx,

			func() (any, *http.Response, error) {
				pagedIterator := r.Client.ManagementAPIClient.ResourceScopesApi.ReadAllResourceScopes(ctx, data.EnvironmentId.ValueString()).Execute()

				var initialHttpResponse *http.Response

				for pageCursor, err := range pagedIterator {
					if err != nil {
						return framework.CheckEnvironmentExistsOnPermissionsErrorLegacySdk(ctx, r.Client.ManagementAPIClient, data.EnvironmentId.ValueString(), nil, pageCursor.HTTPResponse, err)
					}

					if initialHttpResponse == nil {
						initialHttpResponse = pageCursor.HTTPResponse
					}

					if results, ok := pageCursor.EntityArray.Embedded.GetScopesOk(); ok {

						for _, resultObj := range results {
							if resultObj.Name == data.Name.ValueString() {
								return resultObj, pageCursor.HTTPResponse, nil
							}
						}
					}
				}

				return nil, initialHttpResponse, nil
			},
			"ReadAllResourceScopes",
			framework.DefaultCustomError,
			sdk.DefaultCreateReadRetryable,
			&responseData,
		)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if responseData == nil {
			resp.Diagnostics.AddError(
				"Cannot find the resource_scopes from name",
				fmt.Sprintf("The resource_scopes name %s for environment %s cannot be found", data.Name.ValueString(), data.EnvironmentId.ValueString()),
			)
			return
		}
	} else {
		resp.Diagnostics.AddError(
			"Missing parameter",
			"Cannot find the requested resource_scopes. resource_id or name must be set.",
		)
		return
	}

	// Read response into the model
	resp.Diagnostics.Append(data.readClientResponse(responseData)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
