// Copyright © 2026 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package sso

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework/customtypes/pingonetypes"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework/legacysdk"
)

var (
	_ datasource.DataSource              = &passwordPoliciesDataSource{}
	_ datasource.DataSourceWithConfigure = &passwordPoliciesDataSource{}
)

func NewPasswordPoliciesDataSource() datasource.DataSource {
	return &passwordPoliciesDataSource{}
}

type passwordPoliciesDataSource serviceClientType

func (r *passwordPoliciesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_password_policies"
}

func (r *passwordPoliciesDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	resourceConfig, ok := req.ProviderData.(legacysdk.ResourceType)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected the provider client, got: %T. Please report this issue to the provider maintainers.", req.ProviderData),
		)

		return
	}

	r.Client = resourceConfig.Client.API
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Client not initialised",
			"Expected the PingOne client, got nil.  Please report this issue to the provider maintainers.",
		)
		return
	}
}

type passwordPoliciesDataSourceModel struct {
	EnvironmentId pingonetypes.ResourceIDValue `tfsdk:"environment_id"`
	Id            pingonetypes.ResourceIDValue `tfsdk:"id"`
	Ids           types.Set                    `tfsdk:"ids"`
}

func (r *passwordPoliciesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Data source to retrieve all password policies.",
		Attributes: map[string]schema.Attribute{
			"environment_id": framework.Attr_LinkID(
				framework.SchemaAttributeDescriptionFromMarkdown("The ID of the environment to read password policies from. Must be a valid PingOne resource ID."),
			),
			"id": framework.Attr_ID(),
			"ids": schema.SetAttribute{
				ElementType: pingonetypes.ResourceIDType{},
				Computed:    true,
				Description: "The list of resulting IDs of password policies that have been successfully retrieved.",
			},
		},
	}
}

func (state *passwordPoliciesDataSourceModel) readClientResponse(response []string) diag.Diagnostics {
	var respDiags diag.Diagnostics
	state.Id = framework.PingOneResourceIDToTF(state.EnvironmentId.ValueString())
	state.Ids, respDiags = framework.StringSliceToTFSet(response)
	return respDiags
}

func (r *passwordPoliciesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data passwordPoliciesDataSourceModel

	if r.Client == nil || r.Client.ManagementAPIClient == nil {
		resp.Diagnostics.AddError(
			"Client not initialized",
			"Expected the PingOne client, got nil.  Please report this issue to the provider maintainers.")
		return
	}

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Read API call logic
	var responseData []string
	resp.Diagnostics.Append(legacysdk.ParseResponse(
		ctx,

		func() (any, *http.Response, error) {
			pagedIterator := r.Client.ManagementAPIClient.PasswordPoliciesApi.ReadAllPasswordPolicies(ctx, data.EnvironmentId.ValueString()).Execute()

			var initialHttpResponse *http.Response

			for pageCursor, err := range pagedIterator {
				if err != nil {
					return legacysdk.CheckEnvironmentExistsOnPermissionsError(ctx, r.Client.ManagementAPIClient, data.EnvironmentId.ValueString(), nil, pageCursor.HTTPResponse, err)
				}

				if initialHttpResponse == nil {
					initialHttpResponse = pageCursor.HTTPResponse
				}

				if results, ok := pageCursor.EntityArray.Embedded.GetPasswordPoliciesOk(); ok {

					for _, resultObj := range results {
						id, ok := resultObj.GetIdOk()
						if ok {
							responseData = append(responseData, *id)
						}
					}
				}
			}

			return nil, initialHttpResponse, nil
		},
		"ReadAllPasswordPolicies",
		legacysdk.DefaultCustomError,
		nil,
		&responseData,
	)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read response into the model
	resp.Diagnostics.Append(data.readClientResponse(responseData)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
