// Copyright © 2026 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package sso_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest/service/sso"
	"github.com/pingidentity/terraform-provider-pingone/internal/verify"
)

func TestAccPasswordPoliciesDataSource_Get(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckNoTestAccFlaky(t)
			acctest.PreCheckClient(t)
			acctest.PreCheckNoBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             sso.PasswordPolicy_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: testAccPasswordPoliciesDataSourceConfig_Get(resourceName),
				Check:  passwordPoliciesDataSource_CheckComputedValuesComplete(resourceName),
			},
		},
	})
}

func testAccPasswordPoliciesDataSourceConfig_Get(resourceName string) string {
	return fmt.Sprintf(`
	%[1]s

resource "pingone_password_policy" "%[2]s-policy1" {
  environment_id = data.pingone_environment.general_test.id
  name           = "%[2]s-policy1"
}

resource "pingone_password_policy" "%[2]s-policy2" {
  environment_id = data.pingone_environment.general_test.id
  name           = "%[2]s-policy2"
}

resource "pingone_password_policy" "%[2]s-policy3" {
  environment_id = data.pingone_environment.general_test.id
  name           = "%[2]s-policy3"
}

data "pingone_password_policies" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id

  depends_on = [
    pingone_password_policy.%[2]s-policy1,
    pingone_password_policy.%[2]s-policy2,
    pingone_password_policy.%[2]s-policy3,
  ]
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

// Validate any computed values when applying complete HCL
func passwordPoliciesDataSource_CheckComputedValuesComplete(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_password_policies.%s", resourceName), "environment_id", verify.P1ResourceIDRegexpFullString),
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_password_policies.%s", resourceName), "id", verify.P1ResourceIDRegexpFullString),
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_password_policies.%s", resourceName), "ids.0", verify.P1ResourceIDRegexpFullString),
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_password_policies.%s", resourceName), "ids.1", verify.P1ResourceIDRegexpFullString),
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_password_policies.%s", resourceName), "ids.2", verify.P1ResourceIDRegexpFullString),
	)
}
