// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package base_test

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest/service/base"
	client "github.com/pingidentity/terraform-provider-pingone/internal/client"
)

func TestAccLanguageTranslation_RemovalDrift(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_language_translation.%s", resourceName)

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")
	var environmentId string
	var locale string

	var p1Client *client.Client
	var ctx = context.Background()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckNoFeatureFlag(t)

			p1Client = acctest.PreCheckTestClient(ctx, t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Test removal of the environment
			{
				Config: languageTranslation_NewEnvHCL(environmentName, licenseID, resourceName),
				Check:  languageTranslation_GetIDs(resourceFullName, &environmentId, &locale),
			},
			{
				PreConfig: func() {
					base.Environment_RemovalDrift_PreConfig(ctx, p1Client.API.ManagementAPIClient, t, environmentId)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestAccLanguageTranslation_Full(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_language_translation.%s", resourceName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
				Check:  languageTranslation_CheckComputedValuesUpdated(resourceName),
			},
			{
				// Test importing the resource
				Config:       languageTranslation_UpdatedHCL(resourceName),
				ResourceName: fmt.Sprintf("pingone_language_translation.%s", resourceName),
				ImportStateIdFunc: func() resource.ImportStateIdFunc {
					return func(s *terraform.State) (string, error) {
						rs, ok := s.RootModule().Resources[resourceFullName]
						if !ok {
							return "", fmt.Errorf("Resource Not found: %s", resourceFullName)
						}

						return fmt.Sprintf("%s/%s/%s", rs.Primary.Attributes["environment_id"], rs.Primary.Attributes["locale"], rs.Primary.Attributes["id"]), nil
					}
				}(),
				ImportStateVerifyIdentifierAttribute: "id",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
		},
	})
}

func TestAccLanguageTranslation_Change(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
				Check:  languageTranslation_CheckComputedValuesUpdated(resourceName),
			},
			{
				Config: languageTranslation_InitialHCL(resourceName),
				Check:  languageTranslation_CheckComputedValuesMinimal(resourceName),
			},
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
				Check:  languageTranslation_CheckComputedValuesUpdated(resourceName),
			},
		},
	})
}

func TestAccLanguageTranslation_NewEnv(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: languageTranslation_NewEnvHCL(environmentName, licenseID, resourceName),
				Check:  languageTranslation_CheckComputedValuesMinimal(resourceName),
			},
		},
	})
}
func TestAccLanguageTranslation_BadParameters(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_language_translation.%s", resourceName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Configure
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
			},
			// Errors
			{
				ResourceName: resourceFullName,
				ImportState:  true,
				ExpectError:  regexp.MustCompile(`Unexpected Import Identifier`),
			},
			{
				ResourceName:  resourceFullName,
				ImportStateId: "/",
				ImportState:   true,
				ExpectError:   regexp.MustCompile(`Unexpected Import Identifier`),
			},
			{
				ResourceName:  resourceFullName,
				ImportStateId: "badformat/badformat",
				ImportState:   true,
				ExpectError:   regexp.MustCompile(`Unexpected Import Identifier`),
			},
		},
	})
}

// Initial HCL with original required values set
func languageTranslation_InitialHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_language_translation" "%[2]s" {
  environment_id  = data.pingone_environment.general_test.id
  locale          = "en"
  key             = "flow-ui.button.createNewAccount"
  translated_text = "Create new Account"
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

// Updated HCL with values updated to reflect a change
func languageTranslation_UpdatedHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_language_translation" "%[2]s" {
  environment_id  = data.pingone_environment.general_test.id
  locale          = "en"
  key             = "flow-ui.button.createNewAccount"
  translated_text = "Update New Account"
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

func languageTranslation_NewEnvHCL(environmentName, licenseID, resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_language_translation" "%[3]s" {
  environment_id  = pingone_environment.%[2]s.id
  locale          = "en"
  key             = "flow-ui.button.createNewAccount"
  translated_text = "Create new Account"
}
`, acctest.MinimalSandboxEnvironment(environmentName, licenseID), environmentName, resourceName)
}

// Validate any computed values when applying minimal HCL
func languageTranslation_CheckComputedValuesMinimal(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "short_key", "button.createNewAccount"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "reference_text", "Create new Account"),
	)
}

// Validate any computed values when applying updated HCL
func languageTranslation_CheckComputedValuesUpdated(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "short_key", "button.createNewAccount"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "reference_text", "Update New Account"),
	)
}

func languageTranslation_GetIDs(resourceName string, environmentId, id *string) resource.TestCheckFunc {
	return func(s *terraform.State) error {

		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("Resource Not found: %s", resourceName)
		}
		if environmentId != nil {
			*environmentId = rs.Primary.Attributes["environment_id"]
		}
		if id != nil {
			*id = rs.Primary.Attributes["id"]
		}

		return nil
	}
}
