// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package base_test

import (
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest/service/base"
	client "github.com/pingidentity/terraform-provider-pingone/internal/client"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework"
)

func TestAccLanguageTranslation_RemovalDrift(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_language_translation.%s", resourceName)

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")
	var environmentId string
	var locale string

	var p1Client *client.Client
	var ctx = context.Background()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckNoTestAccFlaky(t)
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckNoFeatureFlag(t)

			p1Client = acctest.PreCheckTestClient(ctx, t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Test removal of the environment
			{
				Config: languageTranslation_NewEnvHCL(environmentName, licenseID, resourceName),
				Check:  languageTranslation_GetIDs(resourceFullName, &environmentId, &locale),
			},
			{
				PreConfig: func() {
					base.Environment_RemovalDrift_PreConfig(ctx, p1Client.API.ManagementAPIClient, t, environmentId)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestAccLanguageTranslation_Full(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckNoTestAccFlaky(t)
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		CheckDestroy:             languageTranslation_CheckDestroy,
		Steps: []resource.TestStep{
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
				Check:  languageTranslation_CheckUpdatedComputedValues(resourceName),
			},
			{
				Config:  languageTranslation_UpdatedHCL(resourceName),
				Destroy: true,
			},
			{
				Config: languageTranslation_InitialHCL(resourceName),
				Check:  languageTranslation_CheckInitialComputedValues(resourceName),
			},
			{
				Config:  languageTranslation_InitialHCL(resourceName),
				Destroy: true,
			},
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
				Check:  languageTranslation_CheckUpdatedComputedValues(resourceName),
			},
			{
				Config: languageTranslation_InitialHCL(resourceName),
				Check:  languageTranslation_CheckInitialComputedValues(resourceName),
			},
			{
				Config: languageTranslation_UpdatedHCL(resourceName),
				Check:  languageTranslation_CheckUpdatedComputedValues(resourceName),
			},
		},
	})
}

func TestAccLanguageTranslation_NewEnv(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckNoTestAccFlaky(t)
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: languageTranslation_NewEnvHCL(environmentName, licenseID, resourceName),
				Check:  languageTranslation_CheckInitialComputedValues(resourceName),
			},
		},
	})
}

// Initial HCL with original required values set
func languageTranslation_InitialHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_language" "sv" {
  environment_id = data.pingone_environment.general_test.id

  locale = "sv"
}

resource "pingone_language_translation" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  locale         = pingone_language.sv.locale
  translations = [
    {
      key = "flow-ui.button.createNewAccount"
    }
  ]
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

// Updated HCL with values updated to reflect a change
func languageTranslation_UpdatedHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_language_translation" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  locale         = "sv"
  translations = [
    {
      key             = "flow-ui.button.createNewAccount"
      translated_text = "Skapa nytt konto"
    }
  ]
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

func languageTranslation_NewEnvHCL(environmentName, licenseID, resourceName string) string {
	return fmt.Sprintf(`
		%[1]s
resource "pingone_language" "sv" {
  environment_id = pingone_environment.%[2]s.id

  locale = "sv"
}

resource "pingone_language_translation" "%[3]s" {
  environment_id = pingone_environment.%[2]s.id
  locale         = pingone_language.sv.locale
  translations = [
    {
      key = "flow-ui.button.createNewAccount"
    }
  ]
}
`, acctest.MinimalSandboxEnvironment(environmentName, licenseID), environmentName, resourceName)
}

func languageTranslation_CheckInitialComputedValues(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "translations.0.short_key", "button.createNewAccount"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "translations.0.reference_text", "Create new Account"),
	)
}

func languageTranslation_CheckUpdatedComputedValues(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "translations.0.short_key", "button.createNewAccount"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "translations.0.reference_text", "Create new Account"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_language_translation.%s", resourceName), "translations.0.translated_text", "Skapa nytt konto"),
	)
}

func languageTranslation_GetIDs(resourceName string, environmentId, id *string) resource.TestCheckFunc {
	return func(s *terraform.State) error {

		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("Resource Not found: %s", resourceName)
		}
		if environmentId != nil {
			*environmentId = rs.Primary.Attributes["environment_id"]
		}
		if id != nil {
			*id = rs.Primary.Attributes["id"]
		}

		return nil
	}
}

func languageTranslation_CheckDestroy(s *terraform.State) error {
	var ctx = context.Background()

	p1Client, err := acctest.TestClient(ctx)

	if err != nil {
		return err
	}

	apiClient := p1Client.API.ManagementAPIClient

	for _, rs := range s.RootModule().Resources {
		if rs.Type != "pingone_language_translation" {
			continue
		}

		shouldContinue, err := acctest.CheckParentEnvironmentDestroy(ctx, apiClient, rs.Primary.Attributes["environment_id"])
		if err != nil {
			return err
		}

		if shouldContinue {
			continue
		}

		found := false
		pagedIterator := apiClient.TranslationsApi.ReadTranslations(ctx, rs.Primary.Attributes["environment_id"], rs.Primary.Attributes["locale"]).Execute()

		for pageCursor, err := range pagedIterator {
			if err != nil {
				_, _, err := framework.CheckEnvironmentExistsOnPermissionsError(ctx, apiClient, rs.Primary.Attributes["environment_id"], nil, pageCursor.HTTPResponse, err)
				return err
			}

			if translations, ok := pageCursor.EntityArray.Embedded.GetTranslationsOk(); ok {
				for _, translation := range translations {
					// verifying the translation text is back to the original value for the `fr` locale
					if v, ok := translation.GetIdOk(); ok && *v == rs.Primary.Attributes["id"] && translation.TranslatedText == "Créer un nouveau compte" {
						found = true
						break
					}
				}
			}
		}

		if !found {
			continue
		}

		return fmt.Errorf("PingOne Language Translation %s still exists", rs.Primary.ID)
	}

	return nil
}
