// Copyright © 2026 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

//go:build beta

package davinci_test

import (
	"fmt"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest"
	"github.com/pingidentity/terraform-provider-pingone/internal/verify"
)

func TestAccDavinciApplicationDataSource_ByIDFull_Clean(t *testing.T) {
	testAccDavinciApplicationDataSource_ByIDFull(t, false)
}

func TestAccDavinciApplicationDataSource_ByIDFull_WithBootstrap(t *testing.T) {
	testAccDavinciApplicationDataSource_ByIDFull(t, true)
}

func testAccDavinciApplicationDataSource_ByIDFull(t *testing.T, withBootstrapConfig bool) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciApplication_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: testAccDavinciApplicationDataSourceConfig_ByIDFull(resourceName, withBootstrapConfig),
				Check:  davinciApplicationDataSource_CheckComputedValuesComplete(resourceName),
			},
		},
	})
}

func TestAccDavinciApplicationDataSource_BootstrapApplicationByIDFull(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: testAccDavinciApplicationDataSourceConfig_BootstrapApplicationByID(resourceName),
				Check:  davinciApplicationDataSource_CheckComputedValuesBootstrapApplication(resourceName),
			},
		},
	})
}

func TestAccDavinciApplicationDataSource_NotFound_Clean(t *testing.T) {
	testAccDavinciApplicationDataSource_NotFound(t, false)
}

func TestAccDavinciApplicationDataSource_NotFound_WithBootstrap(t *testing.T) {
	testAccDavinciApplicationDataSource_NotFound(t, true)
}

func testAccDavinciApplicationDataSource_NotFound(t *testing.T, withBootstrapConfig bool) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciApplication_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config:      testAccDavinciApplicationDataSourceConfig_NotFoundByID(resourceName, withBootstrapConfig),
				ExpectError: regexp.MustCompile("The requested resource was not found"),
			},
		},
	})
}

func testAccDavinciApplicationDataSourceConfig_Full(resourceName string) string {
	return fmt.Sprintf(`
resource "pingone_davinci_application" "%[1]s" {
  environment_id = data.pingone_environment.general_test.id
  name           = "%[1]s"
  api_key = {
    enabled = false
  }
  oauth = {
    enforce_signed_request_openid = true
    grant_types = [
      "clientCredentials",
      "authorizationCode",
      "implicit",
    ]
    logout_uris = [
      "https://pingidentity.com/logout",
    ]
    redirect_uris = [
      "https://pingidentity.com/callback",
      "https://pingidentity.com/redirect",
    ]
    scopes = [
      "profile",
      "flow_analytics",
      "openid",
    ]
    sp_jwks_url = "https://pingidentity.com/jwks"
  }
}
`, resourceName)
}

func testAccDavinciApplicationDataSourceConfig_ByIDFull(resourceName string, withBootstrapConfig bool) string {
	return fmt.Sprintf(`
	%[1]s

    %[3]s

data "pingone_davinci_application" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  application_id = pingone_davinci_application.%[2]s.id
}`, acctest.DaVinciSandboxEnvironment(withBootstrapConfig), resourceName, testAccDavinciApplicationDataSourceConfig_Full(resourceName))
}

func testAccDavinciApplicationDataSourceConfig_BootstrapApplicationByID(resourceName string) (hcl string) {
	return fmt.Sprintf(`
%[1]s

data "pingone_davinci_applications" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
}

data "pingone_davinci_application" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  application_id = data.pingone_davinci_applications.%[2]s.davinci_applications.* [index(data.pingone_davinci_applications.%[2]s.davinci_applications[*].name, "PingOne SSO Connection")].id
}
`, acctest.DaVinciSandboxEnvironment(true), resourceName)
}

func testAccDavinciApplicationDataSourceConfig_NotFoundByID(resourceName string, withBootstrapConfig bool) string {
	return fmt.Sprintf(`
	%[1]s

data "pingone_davinci_application" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  application_id = "9c052a8a-14be-44e4-8f07-2662569994ce" // dummy ID that conforms to UUID v4
}
`, acctest.DaVinciSandboxEnvironment(withBootstrapConfig), resourceName)
}

// Validate any computed values when applying complete HCL
func davinciApplicationDataSource_CheckComputedValuesComplete(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "api_key.enabled", "false"),
		resource.TestCheckResourceAttrSet(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "api_key.value"),
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "id", verify.P1DVResourceIDRegexp),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "name", resourceName),
		resource.TestCheckResourceAttrSet(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.client_secret"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.enforce_signed_request_openid", "true"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.grant_types.#", "3"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.grant_types.*", "clientCredentials"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.grant_types.*", "authorizationCode"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.grant_types.*", "implicit"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.logout_uris.#", "1"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.logout_uris.*", "https://pingidentity.com/logout"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.redirect_uris.#", "2"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.redirect_uris.*", "https://pingidentity.com/callback"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.redirect_uris.*", "https://pingidentity.com/redirect"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.#", "3"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.*", "profile"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.*", "flow_analytics"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.*", "openid"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.sp_jwks_openid"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.sp_jwks_url", "https://pingidentity.com/jwks"),
	)
}

func davinciApplicationDataSource_CheckComputedValuesBootstrapApplication(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "api_key.enabled", "true"),
		resource.TestCheckResourceAttrSet(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "api_key.value"),
		resource.TestMatchResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "id", verify.P1DVResourceIDRegexp),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "name", "PingOne SSO Connection"),
		resource.TestCheckResourceAttrSet(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.client_secret"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.enforce_signed_request_openid"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.grant_types.#", "1"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.grant_types.*", "authorizationCode"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.logout_uris"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.redirect_uris.#", "1"),
		resource.TestCheckResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.#", "2"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.*", "profile"),
		resource.TestCheckTypeSetElemAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.scopes.*", "openid"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.sp_jwks_openid"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("data.pingone_davinci_application.%s", resourceName), "oauth.sp_jwks_url"),
	)
}
