// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package davinci

import (
	"context"
	"fmt"
	"net/http"
	"regexp"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pingidentity/pingone-go-client/pingone"
	"github.com/pingidentity/terraform-provider-pingone/internal/framework"
)

var (
	_ datasource.DataSource              = &davinciConnectorInstanceDataSource{}
	_ datasource.DataSourceWithConfigure = &davinciConnectorInstanceDataSource{}
)

func NewDavinciConnectorInstanceDataSource() datasource.DataSource {
	return &davinciConnectorInstanceDataSource{}
}

type davinciConnectorInstanceDataSource serviceClientType

func (r *davinciConnectorInstanceDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_davinci_connector_instance"
}

func (r *davinciConnectorInstanceDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	resourceConfig, ok := req.ProviderData.(framework.ResourceType)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected the provider client, got: %T. Please report this issue to the provider maintainers.", req.ProviderData),
		)

		return
	}

	r.Client = resourceConfig.Client
	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Client not initialised",
			"Expected the PingOne client, got nil.  Please report this issue to the provider maintainers.",
		)
		return
	}
}

type davinciConnectorInstanceDataSourceModel struct {
	Connector     types.Object `tfsdk:"connector"`
	EnvironmentId types.String `tfsdk:"environment_id"`
	Id            types.String `tfsdk:"id"`
	InstanceId    types.String `tfsdk:"instance_id"`
	Name          types.String `tfsdk:"name"`
	Properties    types.Object `tfsdk:"properties"`
}

func (r *davinciConnectorInstanceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Data source to retrieve a davinci_connector_instance.",
		Attributes: map[string]schema.Attribute{
			"connector": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed: true,
					},
				},
				Computed: true,
			},
			"environment_id": schema.StringAttribute{
				Required:    true,
				Description: "The ID of the environment that is configured with the instance. Must be a valid PingOne resource ID.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"), "Must be a valid UUID"),
				},
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "The ID of this data source.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"), "Must be a valid UUID"),
				},
			},
			"instance_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A string that specifies the ID of the instance to retrieve configuration for. Must be a valid PingOne resource ID. Exactly one of \"name\" or \"instance_id\" must be defined.",
				MarkdownDescription: "A string that specifies the ID of the instance to retrieve configuration for. Must be a valid PingOne resource ID. Exactly one of `name` or `instance_id` must be defined.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"), "Must be a valid UUID"),
					stringvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("name")),
				},
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A string that specifies the name of the instance to retrieve configuration for. Exactly one of \"name\" or \"instance_id\" must be defined.",
				MarkdownDescription: "A string that specifies the name of the instance to retrieve configuration for. Exactly one of `name` or `instance_id` must be defined.",
				Validators: []validator.String{
					stringvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("instance_id")),
					stringvalidator.LengthAtLeast(1),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				Computed:   true,
			},
		},
	}
}

func (state *davinciConnectorInstanceDataSourceModel) readClientResponse(response *pingone.DaVinciConnectorInstance) diag.Diagnostics {
	var respDiags, diags diag.Diagnostics
	// connector
	connectorAttrTypes := map[string]attr.Type{
		"id": types.StringType,
	}
	connectorValue, diags := types.ObjectValue(connectorAttrTypes, map[string]attr.Value{
		"id": types.StringValue(response.Connector.Id),
	})
	respDiags.Append(diags...)
	state.Connector = connectorValue
	// id
	state.Id = types.StringPointerValue(response.Id)
	// instance_id
	state.InstanceId = types.StringPointerValue(response.Id)
	// name
	state.Name = types.StringValue(response.Name)
	// properties
	propertiesAttrTypes := map[string]attr.Type{}
	var propertiesValue types.Object
	if response.Properties == nil {
		propertiesValue = types.ObjectNull(propertiesAttrTypes)
	} else {
		propertiesValue, diags = types.ObjectValue(propertiesAttrTypes, map[string]attr.Value{})
		respDiags.Append(diags...)
	}
	state.Properties = propertiesValue
	return respDiags
}

func (r *davinciConnectorInstanceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data davinciConnectorInstanceDataSourceModel

	if r.Client == nil {
		resp.Diagnostics.AddError(
			"Client not initialized",
			"Expected the PingOne client, got nil.  Please report this issue to the provider maintainers.")
		return
	}

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Read API call logic
	environmentIdUuid, err := uuid.Parse(data.EnvironmentId.ValueString())
	if err != nil {
		resp.Diagnostics.AddAttributeError(
			path.Root("environment_id"),
			"Attribute Validation Error",
			fmt.Sprintf("The value '%s' for attribute '%s' is not a valid UUID: %s", data.EnvironmentId.ValueString(), "EnvironmentId", err.Error()),
		)
		return
	}
	var responseData *pingone.DaVinciConnectorInstance
	resp.Diagnostics.Append(framework.ParseResponse(
		ctx,

		func() (any, *http.Response, error) {
			fO, fR, fErr := r.Client.DaVinciConnectorApi.GetConnectorInstanceById(ctx, environmentIdUuid, data.InstanceId.ValueString()).Execute()
			return framework.CheckEnvironmentExistsOnPermissionsError(ctx, r.Client, data.EnvironmentId.ValueString(), fO, fR, fErr)
		},
		"GetConnectorInstanceById",
		framework.DefaultCustomError,
		&responseData,
	)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Read response into the model
	resp.Diagnostics.Append(data.readClientResponse(responseData)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
