// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

package davinci_test

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"testing"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/pingidentity/pingone-go-client/pingone"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest"
	acctestlegacysdk "github.com/pingidentity/terraform-provider-pingone/internal/acctest/legacysdk"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest/service/base"
)

func TestAccDavinciVariable_RemovalDrift(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_davinci_variable.%s", resourceName)

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")
	var environmentId string
	var id string

	var p1Client *pingone.APIClient
	var ctx = context.Background()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckNoFeatureFlag(t)

			p1Client = acctest.PreCheckTestClient(ctx, t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Configure
			{
				Config: davinciVariable_MinimalHCL(resourceName),
				Check:  davinciVariable_GetIDs(resourceFullName, &environmentId, &id),
			},
			{
				PreConfig: func() {
					davinciVariable_Delete(ctx, p1Client, t, environmentId, id)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
			// Test removal of the environment
			{
				Config: davinciVariable_NewEnvHCL(environmentName, licenseID, resourceName),
				Check:  davinciVariable_GetIDs(resourceFullName, &environmentId, &id),
			},
			{
				PreConfig: func() {
					base.Environment_RemovalDrift_PreConfig(ctx, p1Client, t, environmentId)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestAccDavinciVariable_MinimalMaximal(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_davinci_variable.%s", resourceName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: davinciVariable_MinimalHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesMinimal(resourceName),
			},
			{
				// Delete the minimal model
				Config:  davinciVariable_MinimalHCL(resourceName),
				Destroy: true,
			},
			{
				// Re-create with a complete model
				Config: davinciVariable_CompleteHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesComplete(resourceName),
			},
			{
				// Back to minimal model
				Config: davinciVariable_MinimalHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesMinimal(resourceName),
			},
			{
				// Back to complete model
				Config: davinciVariable_CompleteHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesComplete(resourceName),
			},
			{
				// Test importing the resource
				Config:       davinciVariable_CompleteHCL(resourceName),
				ResourceName: fmt.Sprintf("pingone_davinci_variable.%s", resourceName),
				ImportStateIdFunc: func() resource.ImportStateIdFunc {
					return func(s *terraform.State) (string, error) {
						rs, ok := s.RootModule().Resources[resourceFullName]
						if !ok {
							return "", fmt.Errorf("Resource Not found: %s", resourceFullName)
						}

						return fmt.Sprintf("%s/%s", rs.Primary.Attributes["environment_id"], rs.Primary.Attributes["id"]), nil
					}
				}(),
				ImportStateVerifyIdentifierAttribute: "id",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
		},
	})
}

func TestAccDavinciVariable_Boolean(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: davinciVariable_BooleanHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesMinimal(resourceName),
			},
		},
	})
}

func TestAccDavinciVariable_Number(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: davinciVariable_NumberHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesMinimal(resourceName),
			},
		},
	})
}

func TestAccDavinciVariable_Secret(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: davinciVariable_SecretHCL(resourceName),
				Check:  davinciVariable_CheckComputedValuesMinimal(resourceName),
			},
		},
	})
}

func TestAccDavinciVariable_NewEnv(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: davinciVariable_NewEnvHCL(environmentName, licenseID, resourceName),
				Check:  davinciVariable_CheckComputedValuesMinimal(resourceName),
			},
		},
	})
}

func TestAccDavinciVariable_BadParameters(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_davinci_variable.%s", resourceName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNoFeatureFlag(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciVariable_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Configure
			{
				Config: davinciVariable_MinimalHCL(resourceName),
			},
			// Errors
			{
				ResourceName: resourceFullName,
				ImportState:  true,
				ExpectError:  regexp.MustCompile(`Unexpected Import Identifier`),
			},
			{
				ResourceName:  resourceFullName,
				ImportStateId: "/",
				ImportState:   true,
				ExpectError:   regexp.MustCompile(`Unexpected Import Identifier`),
			},
			{
				ResourceName:  resourceFullName,
				ImportStateId: "badformat/badformat",
				ImportState:   true,
				ExpectError:   regexp.MustCompile(`Unexpected Import Identifier`),
			},
		},
	})
}

// Minimal HCL with only required values set
func davinciVariable_MinimalHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_variable" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  context        = "flowInstance"
  data_type      = "string"
  mutable        = true
  name           = "%[2]s"
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

// Maximal HCL with all values set where possible
// TODO test with flow id once we have API/resource available
func davinciVariable_CompleteHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_variable" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  context        = "flowInstance"
  data_type      = "object"
  display_name   = "myobj"
  //   flow = {
  //     id = //TODO
  //   }
  max     = 200
  min     = 0
  mutable = false
  name    = "%[2]s"
  value = {
    json_object = "{\"key1\":\"value1\",\"key2\":1234,\"key3\":false}"
  }
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

func davinciVariable_NewEnvHCL(environmentName, licenseID, resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_variable" "%[3]s" {
  environment_id = pingone_environment.%[2]s.id
  context        = "flowInstance"
  data_type      = "string"
  mutable        = true
  name           = "%[2]s"
}
`, acctestlegacysdk.MinimalSandboxEnvironment(environmentName, licenseID), environmentName, resourceName)
}

// TODO update to cover setting the value bool to false, which currently fails due to an API issue TRIAGE-27920
func davinciVariable_BooleanHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_variable" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  context        = "user"
  data_type      = "boolean"
  mutable        = true
  name           = "%[2]s"
  value = {
    bool = true
  }
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

func davinciVariable_NumberHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_variable" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  context        = "flowInstance"
  data_type      = "number"
  mutable        = false
  name           = "%[2]s"
  value = {
    float32 = 1.23
  }
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

func davinciVariable_SecretHCL(resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_variable" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  context        = "company"
  data_type      = "secret"
  mutable        = false
  name           = "%[2]s"
  value = {
    secret_string = "asdf"
  }
}
`, acctest.GenericSandboxEnvironment(), resourceName)
}

// Validate any computed values when applying minimal HCL
func davinciVariable_CheckComputedValuesMinimal(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckNoResourceAttr(fmt.Sprintf("pingone_davinci_variable.%s", resourceName), "display_name"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_davinci_variable.%s", resourceName), "max", "2000"),
		resource.TestCheckResourceAttr(fmt.Sprintf("pingone_davinci_variable.%s", resourceName), "min", "0"),
	)
}

// Validate any computed values when applying complete HCL
func davinciVariable_CheckComputedValuesComplete(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckNoResourceAttr(fmt.Sprintf("pingone_davinci_variable.%s", resourceName), "value.bool"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("pingone_davinci_variable.%s", resourceName), "value.float32"),
		resource.TestCheckNoResourceAttr(fmt.Sprintf("pingone_davinci_variable.%s", resourceName), "value.string"),
	)
}

func davinciVariable_GetIDs(resourceName string, environmentId, id *string) resource.TestCheckFunc {
	return func(s *terraform.State) error {

		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("Resource Not found: %s", resourceName)
		}
		if environmentId != nil {
			*environmentId = rs.Primary.Attributes["environment_id"]
		}
		if id != nil {
			*id = rs.Primary.Attributes["id"]
		}

		return nil
	}
}

// Delete the resource
func davinciVariable_Delete(ctx context.Context, apiClient *pingone.APIClient, t *testing.T, environmentId, id string) {
	if environmentId == "" || id == "" {
		t.Fatalf("One of the identifier attributes can't be determined. environmentId: '%s' id: '%s'", environmentId, id)
	}

	_, err := apiClient.DaVinciVariableApi.DeleteVariableById(ctx, uuid.MustParse(environmentId), uuid.MustParse(id)).Execute()
	if err != nil {
		t.Fatalf("Failed to delete davinci_variable: %v", err)
	}
}

// Test that any objects created by the test are destroyed
func davinciVariable_CheckDestroy(s *terraform.State) error {
	var ctx = context.Background()

	p1Client, err := acctest.TestClient(ctx)

	if err != nil {
		return err
	}

	for _, rs := range s.RootModule().Resources {
		if rs.Type != "pingone_davinci_variable" {
			continue
		}
		shouldContinue, err := acctest.CheckParentEnvironmentDestroy(ctx, p1Client, rs.Primary.Attributes["environment_id"])
		if err != nil {
			return err
		}

		if shouldContinue {
			continue
		}

		_, r, err := p1Client.DaVinciVariableApi.GetVariableById(ctx, uuid.MustParse(rs.Primary.Attributes["environment_id"]), uuid.MustParse(rs.Primary.Attributes["id"])).Execute()

		shouldContinue, err = acctest.CheckForResourceDestroy(r, err)
		if err != nil {
			return err
		}

		if shouldContinue {
			continue
		}

		return fmt.Errorf("PingOne davinci_variable Instance %s still exists", rs.Primary.ID)
	}

	return nil
}
