// Copyright © 2025 Ping Identity Corporation
// Code generated by ping-terraform-plugin-framework-generator

//go:build beta

package davinci_test

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/pingidentity/pingone-go-client/pingone"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest"
	acctestlegacysdk "github.com/pingidentity/terraform-provider-pingone/internal/acctest/legacysdk"
	"github.com/pingidentity/terraform-provider-pingone/internal/acctest/service/base"
)

func TestAccDavinciFlowEnabled_RemovalDrift(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_davinci_flow_enabled.%s", resourceName)

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")
	var environmentId string
	var id string

	var p1Client *pingone.APIClient
	var ctx = context.Background()

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckBeta(t)

			p1Client = acctest.PreCheckTestClient(ctx, t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciFlow_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Configure
			{
				Config: davinciFlowEnabled_HCL(true, resourceName, false),
				Check:  davinciFlowEnabled_GetIDs(resourceFullName, &environmentId, &id),
			},
			{
				PreConfig: func() {
					davinciFlow_Delete(ctx, p1Client, t, environmentId, id)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
			// Test removal of the environment
			{
				Config: davinciFlowEnabled_NewEnvHCL(true, environmentName, licenseID, resourceName),
				Check:  davinciFlowEnabled_GetIDs(resourceFullName, &environmentId, &id),
			},
			{
				PreConfig: func() {
					base.Environment_RemovalDrift_PreConfig(ctx, p1Client, t, environmentId)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestAccDavinciFlowEnabled_MinimalMaximalClean(t *testing.T) {
	testAccDavinciFlowEnabled_MinimalMaximal(t, false)
}

func TestAccDavinciFlowEnabled_MinimalMaximalWithBootstrap(t *testing.T) {
	testAccDavinciFlowEnabled_MinimalMaximal(t, true)
}

func testAccDavinciFlowEnabled_MinimalMaximal(t *testing.T, withBootstrapConfig bool) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_davinci_flow_enabled.%s", resourceName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciFlow_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				// Create the flow and enable it
				Config: davinciFlowEnabled_HCL(true, resourceName, withBootstrapConfig),
				Check:  davinciFlowEnabled_CheckComputedValues(resourceName),
			},
			{
				// Destroy the config
				Config:  davinciFlowEnabled_HCL(true, resourceName, withBootstrapConfig),
				Destroy: true,
			},
			{
				// Re-create the flow and enable it
				Config: davinciFlowEnabled_HCL(true, resourceName, withBootstrapConfig),
				Check:  davinciFlowEnabled_CheckComputedValues(resourceName),
			},
			{
				// Disable the flow
				Config: davinciFlowEnabled_HCL(false, resourceName, withBootstrapConfig),
				Check:  davinciFlowEnabled_CheckComputedValues(resourceName),
			},
			{
				// Re-enable the flow
				Config: davinciFlowEnabled_HCL(true, resourceName, withBootstrapConfig),
				Check:  davinciFlowEnabled_CheckComputedValues(resourceName),
			},
			{
				// Test importing the resource
				Config:       davinciFlowEnabled_HCL(true, resourceName, withBootstrapConfig),
				ResourceName: fmt.Sprintf("pingone_davinci_flow_enabled.%s", resourceName),
				ImportStateIdFunc: func() resource.ImportStateIdFunc {
					return func(s *terraform.State) (string, error) {
						rs, ok := s.RootModule().Resources[resourceFullName]
						if !ok {
							return "", fmt.Errorf("Resource Not found: %s", resourceFullName)
						}

						return fmt.Sprintf("%s/%s", rs.Primary.Attributes["environment_id"], rs.Primary.Attributes["id"]), nil
					}
				}(),
				ImportStateVerifyIdentifierAttribute: "id",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
		},
	})
}

func TestAccDavinciFlowEnabled_NewEnv(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()

	environmentName := acctest.ResourceNameGenEnvironment()

	licenseID := os.Getenv("PINGONE_LICENSE_ID")

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckNewEnvironment(t)
			acctest.PreCheckBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciFlow_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			{
				Config: davinciFlowEnabled_NewEnvHCL(true, environmentName, licenseID, resourceName),
				Check:  davinciFlowEnabled_CheckComputedValues(resourceName),
			},
		},
	})
}

func TestAccDavinciFlowEnabled_BadParameters(t *testing.T) {
	t.Parallel()

	resourceName := acctest.ResourceNameGen()
	resourceFullName := fmt.Sprintf("pingone_davinci_flow_enabled.%s", resourceName)

	resource.Test(t, resource.TestCase{
		PreCheck: func() {
			acctest.PreCheckClient(t)
			acctest.PreCheckBeta(t)
		},
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		CheckDestroy:             davinciFlow_CheckDestroy,
		ErrorCheck:               acctest.ErrorCheck(t),
		Steps: []resource.TestStep{
			// Configure
			{
				Config: davinciFlowEnabled_HCL(true, resourceName, false),
			},
			// Errors
			{
				ResourceName: resourceFullName,
				ImportState:  true,
				ExpectError:  regexp.MustCompile(`Unexpected Import Identifier`),
			},
			{
				ResourceName:  resourceFullName,
				ImportStateId: "/",
				ImportState:   true,
				ExpectError:   regexp.MustCompile(`Unexpected Import Identifier`),
			},
			{
				ResourceName:  resourceFullName,
				ImportStateId: "badformat/badformat",
				ImportState:   true,
				ExpectError:   regexp.MustCompile(`Unexpected Import Identifier`),
			},
		},
	})
}

func davinciFlowEnabled_HCL(enabled bool, resourceName string, withBootstrapConfig bool) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_flow" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  name           = "%[2]s"
  description    = "This is a demo flow"
  color          = "#00FF00"

  graph_data = {
    elements = {
      nodes = {
        "8bnj41592a" = {
          data = {
            node_type       = "CONNECTION"
            connector_id    = "pingOneSSOConnector"
            label           = "PingOne"
            status          = "configured"
            capability_name = "userLookup"
            type            = "action"
            properties = jsonencode({
              "additionalUserProperties" : {
                "value" : []
              },
              "username" : {
                "value" : "[\n  {\n    \"children\": [\n      {\n        \"text\": \"5282e30d-6e05-499c-ae68-0069fba776f1\"\n      }\n    ]\n  }\n]"
              },
              "population" : {
                "value" : "c9f3fb3f-11e9-4eb0-b4ba-9fb7789a8418"
              },
              "userIdentifierForFindUser" : {
                "value" : "[\n  {\n    \"children\": [\n      {\n        \"text\": \"5282e30d-6e05-499c-ae68-0069fba776f1\"\n      }\n    ]\n  }\n]"
              }
            })
          }
          position = {
            x = 420
            y = 360
          }
          group      = "nodes"
          removed    = false
          selected   = false
          selectable = true
          locked     = false
          grabbable  = true
          pannable   = false
          classes    = ""
        }
      }
    }

    data = "{}"

    box_selection_enabled = true
    user_zooming_enabled  = true
    zooming_enabled       = true
    zoom                  = 1
    min_zoom              = 0.01
    max_zoom              = 10000
    panning_enabled       = true
    user_panning_enabled  = true

    pan = {
      x = 0
      y = 0
    }

    renderer = jsonencode({
      "name" : "null"
    })
  }

  output_schema = {
    output = {
      type                 = "object"
      properties           = jsonencode({})
      additionalProperties = true
    }
  }

  trigger = {
    type = "AUTHENTICATION"
  }
}

resource "pingone_davinci_flow_enabled" "%[2]s" {
  environment_id = data.pingone_environment.general_test.id
  flow_id        = pingone_davinci_flow.%[2]s.id
  enabled        = %[3]t
}
`, acctest.DaVinciSandboxEnvironment(withBootstrapConfig), resourceName, enabled)
}

func davinciFlowEnabled_NewEnvHCL(enabled bool, environmentName, licenseID, resourceName string) string {
	return fmt.Sprintf(`
		%[1]s

resource "pingone_davinci_flow" "%[3]s" {
  environment_id = pingone_environment.%[2]s.id
  name           = "%[3]s"
  description    = "This is a demo flow"
  color          = "#00FF00"

  graph_data = {
    elements = {
      nodes = {
        "8bnj41592a" = {
          data = {
            node_type       = "CONNECTION"
            connector_id    = "pingOneSSOConnector"
            label           = "PingOne"
            status          = "configured"
            capability_name = "userLookup"
            type            = "action"
            properties = jsonencode({
              "additionalUserProperties" : {
                "value" : []
              },
              "username" : {
                "value" : "[\n  {\n    \"children\": [\n      {\n        \"text\": \"5282e30d-6e05-499c-ae68-0069fba776f1\"\n      }\n    ]\n  }\n]"
              },
              "population" : {
                "value" : "c9f3fb3f-11e9-4eb0-b4ba-9fb7789a8418"
              },
              "userIdentifierForFindUser" : {
                "value" : "[\n  {\n    \"children\": [\n      {\n        \"text\": \"5282e30d-6e05-499c-ae68-0069fba776f1\"\n      }\n    ]\n  }\n]"
              }
            })
          }
          position = {
            x = 420
            y = 360
          }
          group      = "nodes"
          removed    = false
          selected   = false
          selectable = true
          locked     = false
          grabbable  = true
          pannable   = false
          classes    = ""
        }
      }
    }

    data = "{}"

    box_selection_enabled = true
    user_zooming_enabled  = true
    zooming_enabled       = true
    zoom                  = 1
    min_zoom              = 0.01
    max_zoom              = 10000
    panning_enabled       = true
    user_panning_enabled  = true

    pan = {
      x = 0
      y = 0
    }

    renderer = jsonencode({
      "name" : "null"
    })
  }

  output_schema = {
    output = {
      type                 = "object"
      properties           = jsonencode({})
      additionalProperties = true
    }
  }

  trigger = {
    type = "AUTHENTICATION"
  }
}

resource "pingone_davinci_flow_enabled" "%[3]s" {
  environment_id = pingone_environment.%[2]s.id
  flow_id        = pingone_davinci_flow.%[3]s.id
  enabled        = %[4]t
}
`, acctestlegacysdk.MinimalSandboxEnvironment(environmentName, licenseID), environmentName, resourceName, enabled)
}

// Validate any computed values
func davinciFlowEnabled_CheckComputedValues(resourceName string) resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttrSet(fmt.Sprintf("pingone_davinci_flow_enabled.%s", resourceName), "id"),
	)
}

func davinciFlowEnabled_GetIDs(resourceName string, environmentId, id *string) resource.TestCheckFunc {
	return func(s *terraform.State) error {

		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("Resource Not found: %s", resourceName)
		}
		if environmentId != nil {
			*environmentId = rs.Primary.Attributes["environment_id"]
		}
		if id != nil {
			*id = rs.Primary.Attributes["id"]
		}

		return nil
	}
}
