# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
# This pipeline runs parallel sets of tests:
#   - the known flaky tests until they can be properly triaged and corrected 
#     through API improvements, test improvements, and so on
#   - tests in which the flaky tests are skipped, for a "clean job" run
# All flaky tests expect the TESTACC_FLAKY environment variable set to true
# in order to be executed.
name: Multi-version Acceptance Tests
on:
  workflow_dispatch:
  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will 
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.
  schedule:
    - cron: '0 6 14,28 * *'
jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          make build

  # prepare the environment
  prepare:
    name: Prepare Environment
    needs: build
    runs-on: ubuntu-latest

    env:
      PINGONE_TESTING_PROVIDER_VERSION: test
      PINGONE_CLIENT_ID: ${{ vars.PINGONE_PROD_EU_CLIENT_ID_CLIENT_SECRET_BASIC }}
      PINGONE_CLIENT_SECRET: ${{ secrets.PINGONE_PROD_EU_CLIENT_SECRET_CLIENT_SECRET_BASIC }}
      PINGONE_ENVIRONMENT_ID: ${{ vars.PINGONE_PROD_EU_ENVIRONMENT_ID }}
      PINGONE_REGION_CODE: "EU"
      PINGONE_LICENSE_ID: ${{ vars.PINGONE_PROD_EU_LICENSE_ID }}
      PINGONE_ORGANIZATION_ID: ${{ vars.PINGONE_PROD_EU_ORG_ID }}

    timeout-minutes: 10

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Sweep to prepare
        run: |
          make sweep

  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Acceptance Test
    needs: [build, prepare]
    runs-on: ubuntu-latest

    env:
      PINGONE_TESTING_PROVIDER_VERSION: test
      PINGONE_CLIENT_ID: ${{ vars.PINGONE_PROD_EU_CLIENT_ID_CLIENT_SECRET_BASIC }}
      PINGONE_CLIENT_SECRET: ${{ secrets.PINGONE_PROD_EU_CLIENT_SECRET_CLIENT_SECRET_BASIC }}
      PINGONE_ENVIRONMENT_ID: ${{ vars.PINGONE_PROD_EU_ENVIRONMENT_ID }}
      PINGONE_REGION_CODE: "EU"
      PINGONE_LICENSE_ID: ${{ vars.PINGONE_PROD_EU_LICENSE_ID }}
      PINGONE_ORGANIZATION_ID: ${{ vars.PINGONE_PROD_EU_ORG_ID }}
      PINGONE_ORGANIZATION_NAME: ${{ secrets.EU_PINGONE_ORGANIZATION_NAME }}
      PINGONE_KEY_PKCS12_UNENCRYPTED: ${{ secrets.PINGONE_KEY_PKCS12_UNENCRYPTED }}
      PINGONE_KEY_PKCS12: ${{ secrets.PINGONE_KEY_PKCS12 }}
      PINGONE_KEY_PKCS12_PASSWORD:  ${{ secrets.PINGONE_KEY_PKCS12_PASSWORD }}
      PINGONE_KEY_PKCS10_CSR: ${{ secrets.PINGONE_KEY_PKCS10_CSR }}
      PINGONE_KEY_PEM_CSR: ${{ secrets.PINGONE_KEY_PEM_CSR }}
      PINGONE_KEY_PEM_CSR_RESPONSE: ${{ secrets.PINGONE_KEY_PEM_CSR_RESPONSE }}
      PINGONE_KEY_PKCS7_CERT: ${{ secrets.PINGONE_KEY_PKCS7_CERT }}
      PINGONE_KEY_PEM_CERT: ${{ secrets.PINGONE_KEY_PEM_CERT }}
      PINGONE_DOMAIN_CERTIFICATE_PEM: ${{ secrets.PINGONE_DOMAIN_CERTIFICATE_PEM }}
      PINGONE_DOMAIN_INTERMEDIATE_CERTIFICATE_PEM: ${{ secrets.PINGONE_DOMAIN_INTERMEDIATE_CERTIFICATE_PEM }}
      PINGONE_DOMAIN_KEY_PEM: ${{ secrets.PINGONE_DOMAIN_KEY_PEM }}
      PINGONE_VERIFIED_EMAIL_DOMAIN: ${{ secrets.PINGONE_VERIFIED_EMAIL_DOMAIN }}
      PINGONE_GOOGLE_JSON_KEY: ${{ secrets.PINGONE_GOOGLE_JSON_KEY }}
      PINGONE_GOOGLE_FIREBASE_CREDENTIALS: ${{ secrets.PINGONE_GOOGLE_JSON_KEY }}
      PINGONE_KEY_PKCS8: ${{ secrets.PINGONE_KEY_PKCS8 }}
      PINGONE_TWILIO_TEST_SKIP: true
      PINGONE_SYNIVERSE_TEST_SKIP: true
      PINGONE_EMAIL_DOMAIN_TEST_SKIP: true

    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform: # We test the earliest supported (v1.4).  The latest supported is in the multi-region test
          - '1.4.*'
      max-parallel: 1

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
        id: go

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Get dependencies
        run: |
          go mod download

      - name: TF acceptance tests
        timeout-minutes: 180
        run: |
          make testacc

  # run acceptance tests in a matrix with Terraform core versions
  # flaky flag set
  test-flaky:
    name: Acceptance Test (FLAKY)
    needs: [build, prepare]
    runs-on: ubuntu-latest
    env:
      TESTACC_FLAKY: true
      PINGONE_TESTING_PROVIDER_VERSION: test
      PINGONE_CLIENT_ID: ${{ vars.PINGONE_PROD_EU_CLIENT_ID_CLIENT_SECRET_BASIC }}
      PINGONE_CLIENT_SECRET: ${{ secrets.PINGONE_PROD_EU_CLIENT_SECRET_CLIENT_SECRET_BASIC }}
      PINGONE_ENVIRONMENT_ID: ${{ vars.PINGONE_PROD_EU_ENVIRONMENT_ID }}
      PINGONE_REGION_CODE: "EU"
      PINGONE_LICENSE_ID: ${{ vars.PINGONE_PROD_EU_LICENSE_ID }}
      PINGONE_ORGANIZATION_ID: ${{ vars.PINGONE_PROD_EU_ORG_ID }}
      PINGONE_ORGANIZATION_NAME: ${{ secrets.EU_PINGONE_ORGANIZATION_NAME }}
      PINGONE_KEY_PKCS12_UNENCRYPTED: ${{ secrets.PINGONE_KEY_PKCS12_UNENCRYPTED }}
      PINGONE_KEY_PKCS12: ${{ secrets.PINGONE_KEY_PKCS12 }}
      PINGONE_KEY_PKCS12_PASSWORD:  ${{ secrets.PINGONE_KEY_PKCS12_PASSWORD }}
      PINGONE_KEY_PKCS10_CSR: ${{ secrets.PINGONE_KEY_PKCS10_CSR }}
      PINGONE_KEY_PEM_CSR: ${{ secrets.PINGONE_KEY_PEM_CSR }}
      PINGONE_KEY_PEM_CSR_RESPONSE: ${{ secrets.PINGONE_KEY_PEM_CSR_RESPONSE }}
      PINGONE_KEY_PKCS7_CERT: ${{ secrets.PINGONE_KEY_PKCS7_CERT }}
      PINGONE_KEY_PEM_CERT: ${{ secrets.PINGONE_KEY_PEM_CERT }}
      PINGONE_DOMAIN_CERTIFICATE_PEM: ${{ secrets.PINGONE_DOMAIN_CERTIFICATE_PEM }}
      PINGONE_DOMAIN_INTERMEDIATE_CERTIFICATE_PEM: ${{ secrets.PINGONE_DOMAIN_INTERMEDIATE_CERTIFICATE_PEM }}
      PINGONE_DOMAIN_KEY_PEM: ${{ secrets.PINGONE_DOMAIN_KEY_PEM }}
      PINGONE_VERIFIED_EMAIL_DOMAIN: ${{ secrets.PINGONE_VERIFIED_EMAIL_DOMAIN }}
      PINGONE_GOOGLE_JSON_KEY: ${{ secrets.PINGONE_GOOGLE_JSON_KEY }}
      PINGONE_GOOGLE_FIREBASE_CREDENTIALS: ${{ secrets.PINGONE_GOOGLE_JSON_KEY }}
      PINGONE_KEY_PKCS8: ${{ secrets.PINGONE_KEY_PKCS8 }}
      PINGONE_TWILIO_TEST_SKIP: true
      PINGONE_SYNIVERSE_TEST_SKIP: true
      PINGONE_EMAIL_DOMAIN_TEST_SKIP: true

    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform: # We test the earliest supported (v1.4).  The latest supported is in the multi-region test
          - '1.4.*'
      max-parallel: 1

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
        id: go

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Get dependencies
        run: |
          go mod download

      - name: TF acceptance tests (flaky)
        id: tf-flaky-acc-test
        continue-on-error: true
        timeout-minutes: 180
        run: |
          make testacc

      - name: Check flaky step status
        run: |
         echo "ACCTEST-FLAKY step outcome: ${{ steps.tf-flaky-acc-test }}"
          if [[ "${{ steps.tf-flaky-acc-test }}" == "failure" ]]; then
           echo "Flaky acceptance tests failed: Continuing..."
         fi

  cleanup:
    name: Acceptance Test
    needs: [test, test-flaky]
    runs-on: ubuntu-latest

    env:
      PINGONE_TESTING_PROVIDER_VERSION: test
      PINGONE_CLIENT_ID: ${{ vars.PINGONE_PROD_EU_CLIENT_ID_CLIENT_SECRET_BASIC }}
      PINGONE_CLIENT_SECRET: ${{ secrets.PINGONE_PROD_EU_CLIENT_SECRET_CLIENT_SECRET_BASIC }}
      PINGONE_ENVIRONMENT_ID: ${{ vars.PINGONE_PROD_EU_ENVIRONMENT_ID }}
      PINGONE_REGION_CODE: "EU"
      PINGONE_LICENSE_ID: ${{ vars.PINGONE_PROD_EU_LICENSE_ID }}
      PINGONE_ORGANIZATION_ID: ${{ vars.PINGONE_PROD_EU_ORG_ID }}

    timeout-minutes: 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Sweep to cleanup
        run: |
          make sweep

  onfailure:
    if: ${{ always() && github.event_name == 'schedule' && contains(needs.*.result, 'failure') }}
    needs: [build, prepare, test, test-flaky, cleanup]
    name: Send failure webhook
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent --request POST "${{ secrets.FAILURE_WEBHOOK_URL }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: text/plain' \
          --data-raw '{
              "WorkflowName": "${{ github.workflow }}",
              "WorkflowURL": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "RepoName" : "${{ github.repository }}",
          }'