name: "Test Webhook"

on:
  push:
    branches: [ "WorkflowFailureWebhook" ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        echo "Build"
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Prepare
      run: |
        echo "Prepare"
    - name: Fail
      run: |
        echo "Fail"
        exit 1
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build, prepare]
    steps:
    - name: Test
      run: |
        echo "Test"
  test-flaky:
    name: Test Flaky
    runs-on: ubuntu-latest
    needs: [build, prepare]
    steps:
    - name: Test Flaky
      run: |
        echo "Test Flaky"
  onfailure:
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs: [build, prepare, test, test-flaky]
    name: On failure
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent --request POST "${{ secrets.FAILURE_WEBHOOK_URL }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: text/plain' \
          --data-raw '{
              "WorkflowName": "${{ github.workflow }}",
              "WorkflowURL": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "RepoName" : "${{ github.repository }}",
          }'
